version: '3.8'

services:
  rule-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev